packages:
  - "apps/*"
  - "packages/*"

engineStrict: true
saveExact: true
strictPeerDependencies: true

allowBuilds:
  esbuild: true
  sharp: true
  unrs-resolver: true

overrides:
  esbuild: 0.28.1
