/**
 * Stable, published error codes thrown by @consultchimps/xlsx. Values are
 * part of the versioned public API; never change an existing value.
 */
export const XLSX_ERRORS = {
  XLSX_DUPLICATE_HEADER: "XLSX_DUPLICATE_HEADER",
  XLSX_EMPTY_HEADER: "XLSX_EMPTY_HEADER",
  XLSX_INPUT_NOT_FOUND: "XLSX_INPUT_NOT_FOUND",
  XLSX_INVALID_EXCEL_TABLE: "XLSX_INVALID_EXCEL_TABLE",
  XLSX_INVALID_HEADER_ROW: "XLSX_INVALID_HEADER_ROW",
  XLSX_INVALID_NAMED_RANGE: "XLSX_INVALID_NAMED_RANGE",
  XLSX_NO_COLUMNS: "XLSX_NO_COLUMNS",
  XLSX_NO_INPUTS: "XLSX_NO_INPUTS",
  XLSX_NO_SHEETS: "XLSX_NO_SHEETS",
  XLSX_NO_TABLES: "XLSX_NO_TABLES",
  XLSX_READ_FAILED: "XLSX_READ_FAILED",
  XLSX_SPLIT_MULTIPLE_TABLES: "XLSX_SPLIT_MULTIPLE_TABLES",
  XLSX_SPLIT_COLUMN_NOT_FOUND: "XLSX_SPLIT_COLUMN_NOT_FOUND",
  XLSX_SPLIT_NO_GROUPS: "XLSX_SPLIT_NO_GROUPS",
  XLSX_SPLIT_NO_TABLE: "XLSX_SPLIT_NO_TABLE",
  XLSX_SPLIT_OUTPUT_NOT_FILE: "XLSX_SPLIT_OUTPUT_NOT_FILE",
  XLSX_SPLIT_PACKAGE_TYPE_MISMATCH: "XLSX_SPLIT_PACKAGE_TYPE_MISMATCH",
  XLSX_SPLIT_PRESERVE_FORMULA: "XLSX_SPLIT_PRESERVE_FORMULA",
  XLSX_SPLIT_PRESERVE_REQUIRES_TABLE: "XLSX_SPLIT_PRESERVE_REQUIRES_TABLE",
  XLSX_SPLIT_PRESERVE_TABLE_NOT_FOUND: "XLSX_SPLIT_PRESERVE_TABLE_NOT_FOUND",
  XLSX_SPLIT_RANGE_HEADER_ROW: "XLSX_SPLIT_RANGE_HEADER_ROW",
  XLSX_SPLIT_ROLLBACK_FAILED: "XLSX_SPLIT_ROLLBACK_FAILED",
  XLSX_SPLIT_TABLE_HEADER_ROW: "XLSX_SPLIT_TABLE_HEADER_ROW",
  XLSX_SPLIT_TABLE_RANGE_CONFLICT: "XLSX_SPLIT_TABLE_RANGE_CONFLICT",
  XLSX_SPLIT_UNSUPPORTED_FILE: "XLSX_SPLIT_UNSUPPORTED_FILE",
  XLSX_WORKSHEET_NOT_FOUND: "XLSX_WORKSHEET_NOT_FOUND",
} as const;

export type XlsxErrorCode = (typeof XLSX_ERRORS)[keyof typeof XLSX_ERRORS];
