export {
  applyColumnMapping,
  applyColumnMappingToTables,
  suggestColumnMapping,
  validateColumnMapping,
  COLUMN_MAPPING_VERSION,
  type CanonicalColumn,
  type ColumnCoercion,
  type ColumnEquivalenceGroup,
  type ColumnHeaderSource,
  type ColumnMapping,
  type ColumnMappingResult,
  type ColumnMappingSuggestion,
  type ColumnMappingTablesResult,
  type ColumnSpellingOccurrence,
  type DateColumnCoercion,
  type NumberColumnCoercion,
} from "./column-mapping.js";
export {
  columnKey,
  groupTableByColumn,
  normalizedColumnKey,
  unionTables,
  uniqueHeaders,
  type CellValue,
  type GroupTableByColumnOptions,
  type GroupTableByColumnResult,
  type Table,
  type TableGroup,
  type TableRow,
  type TableSource,
  type UnionTablesOptions,
} from "./table.js";
