import { readFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

import type { SurfaceStatus } from "../apps/docs/src/lib/tools.ts";
import { TOOLS } from "../apps/docs/src/lib/tools.ts";

// Root README <-> registry conformance check. The README's operations matrix is
// the first thing a visitor reads, and it is hand-written, so it drifts the
// moment an operation is added or a surface flips status, exactly what
// happened when workbook inspection landed and the table still listed six
// tools. The registry in apps/docs/src/lib/tools.ts is the single source of
// truth (ADR 0001), so it is imported directly here, the same way
// scripts/check-registry-site.ts does, rather than re-described.

const workspaceRoot = path.resolve(
  path.dirname(fileURLToPath(import.meta.url)),
  "..",
);
const readmePath = path.join(workspaceRoot, "README.md");
const readmeLabel = "README.md";
const registryLabel = "apps/docs/src/lib/tools.ts";
const tableHeading = "## Operations";

// How each registry status is spelled in the table. A label per status keeps
// the README readable while still being a total function of the registry.
const STATUS_LABELS: Readonly<Record<SurfaceStatus, string>> = {
  works: "Works",
  planned: "Planned",
  none: "None",
};

const EXPECTED_HEADER = ["Operation", "CLI", "Library", "Browser"] as const;

interface TableRow {
  readonly cells: readonly string[];
  /** One-based line number in README.md, for actionable failures. */
  readonly line: number;
}

function splitTableRow(line: string): string[] {
  return line
    .replace(/^\s*\|/, "")
    .replace(/\|\s*$/, "")
    .split("|")
    .map((cell) => cell.trim());
}

function isSeparatorRow(cells: readonly string[]): boolean {
  return cells.every((cell) => /^:?-{3,}:?$/.test(cell));
}

const readmeLines = readFileSync(readmePath, "utf8")
  .replace(/\r\n/g, "\n")
  .split("\n");

const headingIndex = readmeLines.findIndex(
  (line) => line.trim() === tableHeading,
);
if (headingIndex === -1) {
  throw new Error(
    `${readmeLabel} has no "${tableHeading}" heading. The operations matrix is generated by hand but verified against ${registryLabel}; restore the heading and the table beneath it.`,
  );
}

const rows: TableRow[] = [];
for (let index = headingIndex + 1; index < readmeLines.length; index += 1) {
  const line = readmeLines[index] ?? "";
  if (line.trimStart().startsWith("|")) {
    rows.push({ cells: splitTableRow(line), line: index + 1 });
    continue;
  }
  // The table ends at the first non-table line after it has started; prose
  // between the heading and the table is allowed.
  if (rows.length > 0) {
    break;
  }
  if (line.startsWith("#")) {
    break;
  }
}

const problems: string[] = [];
const [headerRow, separatorRow, ...bodyRows] = rows;

if (headerRow === undefined || separatorRow === undefined) {
  throw new Error(
    `${readmeLabel} has a "${tableHeading}" heading with no table under it. Add a table with the columns ${EXPECTED_HEADER.join(
      " | ",
    )}, one row per entry in ${registryLabel}.`,
  );
}

if (headerRow.cells.join("|") !== EXPECTED_HEADER.join("|")) {
  problems.push(
    `line ${headerRow.line}: the table header is "${headerRow.cells.join(
      " | ",
    )}"; it must be "${EXPECTED_HEADER.join(" | ")}"`,
  );
}
if (!isSeparatorRow(separatorRow.cells)) {
  problems.push(
    `line ${separatorRow.line}: expected the Markdown separator row directly under the header`,
  );
}

const expectedRows = TOOLS.map((tool) => [
  tool.title,
  STATUS_LABELS[tool.surfaces.cli],
  STATUS_LABELS[tool.surfaces.library],
  STATUS_LABELS[tool.surfaces.browser.status],
]);

for (const [index, expected] of expectedRows.entries()) {
  const actual = bodyRows[index];
  if (actual === undefined) {
    problems.push(
      `the registry entry "${TOOLS[index]?.slug}" has no row; add "| ${expected.join(
        " | ",
      )} |"`,
    );
    continue;
  }
  if (actual.cells.length !== EXPECTED_HEADER.length) {
    problems.push(
      `line ${actual.line}: expected ${EXPECTED_HEADER.length} columns, found ${actual.cells.length}`,
    );
    continue;
  }
  if (actual.cells.join("|") !== expected.join("|")) {
    problems.push(
      `line ${actual.line}: row reads "${actual.cells.join(
        " | ",
      )}" but registry entry "${TOOLS[index]?.slug}" declares "${expected.join(
        " | ",
      )}"`,
    );
  }
}

for (const extra of bodyRows.slice(expectedRows.length)) {
  problems.push(
    `line ${extra.line}: row "${extra.cells.join(
      " | ",
    )}" has no matching registry entry; register the operation in ${registryLabel} or remove the row`,
  );
}

if (problems.length > 0) {
  throw new Error(
    `The operations matrix in ${readmeLabel} disagrees with the registry in ${registryLabel}:\n${problems
      .map((problem) => `- ${problem}`)
      .join(
        "\n",
      )}\nThe table holds one row per registry entry, in registry order, with each surface spelled ${Object.values(
      STATUS_LABELS,
    )
      .map((label) => `"${label}"`)
      .join(", ")}.`,
  );
}

process.stdout.write(
  `Verified the ${readmeLabel} operations matrix against ${TOOLS.length} registry entries.\n`,
);
