/**
 * The Excel keyboard shortcut database for Windows.
 *
 * Everything here is public knowledge about a widely used application, written
 * in this repository's own words. No client material, no vendor guide text, and
 * no product screenshots are involved.
 *
 * Two conventions the entries follow:
 *
 * - Keys name the physical key. Microsoft's lists write Ctrl+Shift+* and
 *   Ctrl+Shift+~, but the keys a person presses are Ctrl+Shift+8 and
 *   Ctrl+Shift+`, and this page is driven by real presses. Where the published
 *   spelling differs, the note says so.
 * - The ribbon routes are the key tips of English-language Excel. Another
 *   Office display language relabels them, so those sequences lead somewhere
 *   else there; the page says so, and translated route sets are a separate
 *   piece of work.
 * - The category describes what the shortcut does, not how it is typed, so a
 *   ribbon route such as Alt, H, O, I sits with the other column-width
 *   shortcuts. The ribbon sequences category is for the shortcuts that drive
 *   the ribbon itself: the key tips, the tabs, and the File menu.
 *
 * The `mac` field is part of the schema and no entry uses it yet. A macOS pass
 * is a separate piece of work; leaving the field empty is the honest state
 * rather than guessing at translations of these sequences.
 */

import type { ExcelShortcut } from "./excel-shortcuts";

export const EXCEL_SHORTCUTS: readonly ExcelShortcut[] = [
  // Navigation
  {
    id: "nav-move-up",
    keys: [["ArrowUp"]],
    action: "Move the selection one cell up",
    category: "navigation",
  },
  {
    id: "nav-move-down",
    keys: [["ArrowDown"]],
    action: "Move the selection one cell down",
    category: "navigation",
  },
  {
    id: "nav-move-left",
    keys: [["ArrowLeft"]],
    action: "Move the selection one cell left",
    category: "navigation",
  },
  {
    id: "nav-move-right",
    keys: [["ArrowRight"]],
    action: "Move the selection one cell right",
    category: "navigation",
  },
  {
    id: "nav-edge-up",
    keys: [["Ctrl", "ArrowUp"]],
    action: "Jump to the top edge of the current block of data",
    category: "navigation",
    note: "From a blank cell it jumps to the next cell that holds something",
  },
  {
    id: "nav-edge-down",
    keys: [["Ctrl", "ArrowDown"]],
    action: "Jump to the bottom edge of the current block of data",
    category: "navigation",
  },
  {
    id: "nav-edge-left",
    keys: [["Ctrl", "ArrowLeft"]],
    action: "Jump to the left edge of the current block of data",
    category: "navigation",
  },
  {
    id: "nav-edge-right",
    keys: [["Ctrl", "ArrowRight"]],
    action: "Jump to the right edge of the current block of data",
    category: "navigation",
  },
  {
    id: "nav-sheet-start",
    keys: [["Ctrl", "Home"]],
    action: "Go to cell A1 of the worksheet",
    category: "navigation",
    note: "With frozen panes it stops at the first unfrozen cell",
  },
  {
    id: "nav-sheet-end",
    keys: [["Ctrl", "End"]],
    action: "Go to the last cell of the used range",
    category: "navigation",
    note: "The used range can stretch past the visible data until the file is saved again",
  },
  {
    id: "nav-row-start",
    keys: [["Home"]],
    action: "Move to the first column of the current row",
    category: "navigation",
  },
  {
    id: "nav-screen-down",
    keys: [["PageDown"]],
    action: "Move one screen down",
    category: "navigation",
  },
  {
    id: "nav-screen-up",
    keys: [["PageUp"]],
    action: "Move one screen up",
    category: "navigation",
  },
  {
    id: "nav-screen-right",
    keys: [["Alt", "PageDown"]],
    action: "Move one screen to the right",
    category: "navigation",
  },
  {
    id: "nav-screen-left",
    keys: [["Alt", "PageUp"]],
    action: "Move one screen to the left",
    category: "navigation",
  },
  {
    id: "nav-next-sheet",
    keys: [["Ctrl", "PageDown"]],
    action: "Go to the next worksheet",
    category: "navigation",
  },
  {
    id: "nav-previous-sheet",
    keys: [["Ctrl", "PageUp"]],
    action: "Go to the previous worksheet",
    category: "navigation",
  },
  {
    id: "nav-go-to",
    keys: [["Ctrl", "G"]],
    action: "Open the Go To dialog",
    category: "navigation",
    note: "Type a cell reference or pick a named range to jump straight to it",
  },
  {
    id: "nav-go-to-f5",
    keys: [["F5"]],
    action: "Open the Go To dialog",
    category: "navigation",
    note: "The same dialog as Ctrl+G",
  },
  {
    id: "nav-find",
    keys: [["Ctrl", "F"]],
    action: "Open Find",
    category: "navigation",
  },
  {
    id: "nav-replace",
    keys: [["Ctrl", "H"]],
    action: "Open Replace",
    category: "navigation",
  },
  {
    id: "nav-find-next",
    keys: [["Shift", "F4"]],
    action: "Repeat the last search and move to the next match",
    category: "navigation",
  },
  {
    id: "nav-find-previous",
    keys: [["Ctrl", "Shift", "F4"]],
    action: "Repeat the last search and move to the previous match",
    category: "navigation",
  },
  {
    id: "nav-end-mode-right",
    keys: [["End"], ["ArrowRight"]],
    action: "Turn on End mode, then jump to the next edge of data to the right",
    category: "navigation",
    note: "End mode switches itself off once the jump is done",
  },
  {
    id: "nav-end-mode-down",
    keys: [["End"], ["ArrowDown"]],
    action: "Turn on End mode, then jump to the next edge of data below",
    category: "navigation",
  },
  {
    id: "nav-end-mode-home",
    keys: [["End"], ["Home"]],
    action: "Turn on End mode, then move to the last cell of the used range",
    category: "navigation",
  },
  {
    id: "nav-scroll-to-active",
    keys: [["Ctrl", "Backspace"]],
    action: "Scroll the window back to the active cell",
    category: "navigation",
  },
  {
    id: "nav-panes-forward",
    keys: [["F6"]],
    action:
      "Move between the worksheet, the ribbon, an open pane, and the status bar",
    category: "navigation",
  },
  {
    id: "nav-panes-back",
    keys: [["Shift", "F6"]],
    action:
      "Move the other way between the worksheet, the ribbon, and the status bar",
    category: "navigation",
  },

  // Selection
  {
    id: "sel-current-region",
    keys: [["Ctrl", "A"]],
    action:
      "Select the block of data around the active cell, then the whole worksheet",
    category: "selection",
    note: "Press it again to widen the selection. While a function name is being typed it opens the Function Arguments dialog instead",
  },
  {
    id: "sel-whole-worksheet",
    keys: [["Ctrl", "Shift", "Space"]],
    action: "Select the whole worksheet",
    category: "selection",
    note: "Inside a table it selects the table data first, then the whole worksheet",
  },
  {
    id: "sel-row",
    keys: [["Shift", "Space"]],
    action: "Select the whole row",
    category: "selection",
  },
  {
    id: "sel-column",
    keys: [["Ctrl", "Space"]],
    action: "Select the whole column",
    category: "selection",
    note: "Inside a table it selects the table column first",
  },
  {
    id: "sel-extend-up",
    keys: [["Shift", "ArrowUp"]],
    action: "Extend the selection one cell up",
    category: "selection",
  },
  {
    id: "sel-extend-down",
    keys: [["Shift", "ArrowDown"]],
    action: "Extend the selection one cell down",
    category: "selection",
  },
  {
    id: "sel-extend-left",
    keys: [["Shift", "ArrowLeft"]],
    action: "Extend the selection one cell left",
    category: "selection",
  },
  {
    id: "sel-extend-right",
    keys: [["Shift", "ArrowRight"]],
    action: "Extend the selection one cell right",
    category: "selection",
  },
  {
    id: "sel-extend-edge-up",
    keys: [["Ctrl", "Shift", "ArrowUp"]],
    action: "Extend the selection to the top edge of the block of data",
    category: "selection",
  },
  {
    id: "sel-extend-edge-down",
    keys: [["Ctrl", "Shift", "ArrowDown"]],
    action: "Extend the selection to the bottom edge of the block of data",
    category: "selection",
  },
  {
    id: "sel-extend-edge-left",
    keys: [["Ctrl", "Shift", "ArrowLeft"]],
    action: "Extend the selection to the left edge of the block of data",
    category: "selection",
  },
  {
    id: "sel-extend-edge-right",
    keys: [["Ctrl", "Shift", "ArrowRight"]],
    action: "Extend the selection to the right edge of the block of data",
    category: "selection",
  },
  {
    id: "sel-extend-row-start",
    keys: [["Shift", "Home"]],
    action: "Extend the selection to the first column of the row",
    category: "selection",
  },
  {
    id: "sel-extend-sheet-start",
    keys: [["Ctrl", "Shift", "Home"]],
    action: "Extend the selection back to cell A1",
    category: "selection",
  },
  {
    id: "sel-extend-sheet-end",
    keys: [["Ctrl", "Shift", "End"]],
    action: "Extend the selection to the last cell of the used range",
    category: "selection",
  },
  {
    id: "sel-extend-screen-down",
    keys: [["Shift", "PageDown"]],
    action: "Extend the selection one screen down",
    category: "selection",
  },
  {
    id: "sel-extend-screen-up",
    keys: [["Shift", "PageUp"]],
    action: "Extend the selection one screen up",
    category: "selection",
  },
  {
    id: "sel-region-star",
    keys: [["Ctrl", "Shift", "8"]],
    action: "Select the block of data around the active cell",
    category: "selection",
    note: "Published as Ctrl+Shift+*. Inside a PivotTable it selects the whole report",
  },
  {
    id: "sel-visible-cells",
    keys: [["Alt", ";"]],
    action: "Select only the visible cells in the current selection",
    category: "selection",
    note: "Copying after this leaves hidden and filtered rows out",
  },
  {
    id: "sel-extend-mode",
    keys: [["F8"]],
    action: "Turn extend mode on or off so the arrow keys grow the selection",
    category: "selection",
  },
  {
    id: "sel-add-mode",
    keys: [["Shift", "F8"]],
    action: "Turn on add mode to append another range to the selection",
    category: "selection",
  },
  {
    id: "sel-array",
    keys: [["Ctrl", "/"]],
    action: "Select the whole array the active cell belongs to",
    category: "selection",
  },
  {
    id: "sel-row-differences",
    keys: [["Ctrl", "\\"]],
    action:
      "Select the cells in each selected row that differ from the active row",
    category: "selection",
  },
  {
    id: "sel-column-differences",
    keys: [["Ctrl", "Shift", "\\"]],
    action:
      "Select the cells in each selected column that differ from the active column",
    category: "selection",
    note: "Published as Ctrl+Shift+|",
  },
  {
    id: "sel-next-corner",
    keys: [["Ctrl", "."]],
    action: "Move clockwise to the next corner of the selected range",
    category: "selection",
  },
  {
    id: "sel-notes",
    keys: [["Ctrl", "Shift", "O"]],
    action: "Select the cells that carry a note or a comment",
    category: "selection",
  },
  {
    id: "sel-next-sheet",
    keys: [["Ctrl", "Shift", "PageDown"]],
    action: "Add the next worksheet to the selected sheets",
    category: "selection",
  },
  {
    id: "sel-previous-sheet",
    keys: [["Ctrl", "Shift", "PageUp"]],
    action: "Add the previous worksheet to the selected sheets",
    category: "selection",
  },
  {
    id: "sel-go-to-special",
    keys: [["F5"], ["Alt", "S"]],
    action:
      "Open Go To, then Special, to select cells by type such as blanks, formulas, or constants",
    category: "selection",
  },

  // Data entry
  {
    id: "entry-confirm-down",
    keys: [["Enter"]],
    action: "Confirm the entry and move down",
    category: "data entry",
    note: "The direction is set in the Excel options, and inside a selection it stays within the selection",
  },
  {
    id: "entry-confirm-up",
    keys: [["Shift", "Enter"]],
    action: "Confirm the entry and move up",
    category: "data entry",
  },
  {
    id: "entry-confirm-right",
    keys: [["Tab"]],
    action: "Confirm the entry and move one cell right",
    category: "data entry",
    note: "While a formula is being typed it accepts the highlighted suggestion instead",
  },
  {
    id: "entry-confirm-left",
    keys: [["Shift", "Tab"]],
    action: "Confirm the entry and move one cell left",
    category: "data entry",
  },
  {
    id: "entry-new-line",
    keys: [["Alt", "Enter"]],
    action: "Start a new line inside the same cell",
    category: "data entry",
  },
  {
    id: "entry-fill-selection",
    keys: [["Ctrl", "Enter"]],
    action: "Put what was typed into each cell of the selection",
    category: "data entry",
  },
  {
    id: "entry-cancel",
    keys: [["Escape"]],
    action: "Cancel the entry and restore the previous contents",
    category: "data entry",
  },
  {
    id: "entry-edit-cell",
    keys: [["F2"]],
    action: "Edit the active cell in place",
    category: "data entry",
    note: "The cursor lands at the end of the existing contents",
  },
  {
    id: "entry-fill-down",
    keys: [["Ctrl", "D"]],
    action: "Fill the selection down from the top row",
    category: "data entry",
  },
  {
    id: "entry-fill-right",
    keys: [["Ctrl", "R"]],
    action: "Fill the selection right from the first column",
    category: "data entry",
  },
  {
    id: "entry-today",
    keys: [["Ctrl", ";"]],
    action: "Enter today's date as a fixed value",
    category: "data entry",
    note: "The value does not update later, unlike the TODAY function",
  },
  {
    id: "entry-now",
    keys: [["Ctrl", "Shift", ";"]],
    action: "Enter the current time as a fixed value",
    category: "data entry",
  },
  {
    id: "entry-formula-above",
    keys: [["Ctrl", "'"]],
    action: "Copy the formula from the cell above into the active cell",
    category: "data entry",
    note: "References are copied as written, without the usual row shift",
  },
  {
    id: "entry-value-above",
    keys: [["Ctrl", "Shift", "'"]],
    action: "Copy the value from the cell above into the active cell",
    category: "data entry",
    note: 'Published as Ctrl+Shift+"',
  },
  {
    id: "entry-dropdown",
    keys: [["Alt", "ArrowDown"]],
    action: "Open the drop-down list for the active cell",
    category: "data entry",
    note: "Offers the entries already used in the column, a validation list, or a filter menu on a header cell",
  },
  {
    id: "entry-flash-fill",
    keys: [["Ctrl", "E"]],
    action: "Fill the column by following the example already typed",
    category: "data entry",
  },
  {
    id: "entry-copy",
    keys: [["Ctrl", "C"]],
    action: "Copy the selection",
    category: "data entry",
  },
  {
    id: "entry-cut",
    keys: [["Ctrl", "X"]],
    action: "Cut the selection",
    category: "data entry",
  },
  {
    id: "entry-paste",
    keys: [["Ctrl", "V"]],
    action: "Paste the clipboard",
    category: "data entry",
  },
  {
    id: "entry-paste-special",
    keys: [["Ctrl", "Alt", "V"]],
    action: "Open the Paste Special dialog",
    category: "data entry",
  },
  {
    id: "entry-undo",
    keys: [["Ctrl", "Z"]],
    action: "Undo the last action",
    category: "data entry",
  },
  {
    id: "entry-redo",
    keys: [["Ctrl", "Y"]],
    action: "Redo the action that was undone",
    category: "data entry",
  },
  {
    id: "entry-repeat",
    keys: [["F4"]],
    action: "Repeat the last action",
    category: "data entry",
    note: "While a formula is being edited it cycles the reference under the cursor between relative, absolute, and mixed instead",
  },
  {
    id: "entry-insert-cells",
    keys: [["Ctrl", "Shift", "="]],
    action: "Open the Insert dialog for cells, rows, or columns",
    category: "data entry",
    note: "Published as Ctrl+Plus. With a whole row or column selected it inserts one straight away",
  },
  {
    id: "entry-delete-cells",
    keys: [["Ctrl", "-"]],
    action: "Open the Delete dialog for cells, rows, or columns",
    category: "data entry",
  },
  {
    id: "entry-clear-contents",
    keys: [["Delete"]],
    action: "Clear the contents of the selection and leave the formatting",
    category: "data entry",
  },
  {
    id: "entry-clear-and-type",
    keys: [["Backspace"]],
    action: "Clear the active cell and start typing",
    category: "data entry",
    note: "While editing it deletes the character to the left of the cursor",
  },
  {
    id: "entry-delete-to-end",
    keys: [["Ctrl", "Delete"]],
    action: "Delete from the cursor to the end of the line while editing",
    category: "data entry",
  },
  {
    id: "entry-hyperlink",
    keys: [["Ctrl", "K"]],
    action: "Insert or edit a hyperlink",
    category: "data entry",
  },
  {
    id: "entry-formula-bar",
    keys: [["Ctrl", "Shift", "U"]],
    action: "Expand or collapse the formula bar",
    category: "data entry",
  },
  {
    id: "entry-insert-rows",
    keys: [["Alt"], ["H"], ["I"], ["R"]],
    action: "Insert rows above the selection",
    category: "data entry",
  },
  {
    id: "entry-insert-columns",
    keys: [["Alt"], ["H"], ["I"], ["C"]],
    action: "Insert columns to the left of the selection",
    category: "data entry",
  },
  {
    id: "entry-delete-rows",
    keys: [["Alt"], ["H"], ["D"], ["R"]],
    action: "Delete the selected rows",
    category: "data entry",
  },
  {
    id: "entry-delete-columns",
    keys: [["Alt"], ["H"], ["D"], ["C"]],
    action: "Delete the selected columns",
    category: "data entry",
  },
  {
    id: "entry-paste-values",
    keys: [["Alt"], ["H"], ["V"], ["V"]],
    action: "Paste values only",
    category: "data entry",
  },
  {
    id: "entry-paste-formulas",
    keys: [["Alt"], ["H"], ["V"], ["F"]],
    action: "Paste formulas without the source formatting",
    category: "data entry",
  },
  {
    id: "entry-paste-transpose",
    keys: [["Alt"], ["H"], ["V"], ["T"]],
    action: "Paste the copied range with rows and columns swapped",
    category: "data entry",
  },
  {
    id: "entry-paste-special-menu",
    keys: [["Alt"], ["H"], ["V"], ["S"]],
    action: "Open the Paste Special dialog from the ribbon",
    category: "data entry",
  },
  {
    id: "entry-clear-all",
    keys: [["Alt"], ["H"], ["E"], ["A"]],
    action: "Clear the contents and the formatting of the selection",
    category: "data entry",
  },
  {
    id: "entry-clear-contents-ribbon",
    keys: [["Alt"], ["H"], ["E"], ["C"]],
    action: "Clear the contents of the selection from the ribbon",
    category: "data entry",
  },

  // Formatting
  {
    id: "fmt-format-cells",
    keys: [["Ctrl", "1"]],
    action: "Open the Format Cells dialog",
    category: "formatting",
  },
  {
    id: "fmt-bold",
    keys: [["Ctrl", "B"]],
    action: "Turn bold on or off",
    category: "formatting",
  },
  {
    id: "fmt-italic",
    keys: [["Ctrl", "I"]],
    action: "Turn italic on or off",
    category: "formatting",
  },
  {
    id: "fmt-underline",
    keys: [["Ctrl", "U"]],
    action: "Turn underline on or off",
    category: "formatting",
  },
  {
    id: "fmt-strikethrough",
    keys: [["Ctrl", "5"]],
    action: "Turn strikethrough on or off",
    category: "formatting",
  },
  {
    id: "fmt-bold-alternate",
    keys: [["Ctrl", "2"]],
    action: "Turn bold on or off",
    category: "formatting",
    note: "The same result as Ctrl+B",
  },
  {
    id: "fmt-italic-alternate",
    keys: [["Ctrl", "3"]],
    action: "Turn italic on or off",
    category: "formatting",
    note: "The same result as Ctrl+I",
  },
  {
    id: "fmt-underline-alternate",
    keys: [["Ctrl", "4"]],
    action: "Turn underline on or off",
    category: "formatting",
    note: "The same result as Ctrl+U",
  },
  {
    id: "fmt-font-tab",
    keys: [["Ctrl", "Shift", "F"]],
    action: "Open Format Cells with the Font tab in front",
    category: "formatting",
  },
  {
    id: "fmt-font-size",
    keys: [["Ctrl", "Shift", "P"]],
    action: "Open Format Cells at the font settings",
    category: "formatting",
  },
  {
    id: "fmt-general-number",
    keys: [["Ctrl", "Shift", "`"]],
    action: "Apply the General number format",
    category: "formatting",
    note: "Published as Ctrl+Shift+~",
  },
  {
    id: "fmt-number-two-decimals",
    keys: [["Ctrl", "Shift", "1"]],
    action:
      "Apply the number format with two decimals and a thousands separator",
    category: "formatting",
    note: "Published as Ctrl+Shift+!",
  },
  {
    id: "fmt-time",
    keys: [["Ctrl", "Shift", "2"]],
    action: "Apply the time format with hours and minutes",
    category: "formatting",
    note: "Published as Ctrl+Shift+@",
  },
  {
    id: "fmt-date",
    keys: [["Ctrl", "Shift", "3"]],
    action: "Apply the date format with day, month, and year",
    category: "formatting",
    note: "Published as Ctrl+Shift+#",
  },
  {
    id: "fmt-currency",
    keys: [["Ctrl", "Shift", "4"]],
    action: "Apply the currency format with two decimals",
    category: "formatting",
    note: "Published as Ctrl+Shift+$",
  },
  {
    id: "fmt-percent",
    keys: [["Ctrl", "Shift", "5"]],
    action: "Apply the percentage format with no decimals",
    category: "formatting",
    note: "Published as Ctrl+Shift+%",
  },
  {
    id: "fmt-scientific",
    keys: [["Ctrl", "Shift", "6"]],
    action: "Apply the scientific format with two decimals",
    category: "formatting",
    note: "Published as Ctrl+Shift+^",
  },
  {
    id: "fmt-outline-border",
    keys: [["Ctrl", "Shift", "7"]],
    action: "Put an outline border around the selection",
    category: "formatting",
    note: "Published as Ctrl+Shift+&",
  },
  {
    id: "fmt-remove-borders",
    keys: [["Ctrl", "Shift", "-"]],
    action: "Remove the borders from the selection",
    category: "formatting",
    note: "Published as Ctrl+Shift+_",
  },
  {
    id: "fmt-hide-rows",
    keys: [["Ctrl", "9"]],
    action: "Hide the selected rows",
    category: "formatting",
  },
  {
    id: "fmt-unhide-rows",
    keys: [["Ctrl", "Shift", "9"]],
    action: "Unhide the hidden rows inside the selection",
    category: "formatting",
  },
  {
    id: "fmt-hide-columns",
    keys: [["Ctrl", "0"]],
    action: "Hide the selected columns",
    category: "formatting",
  },
  {
    id: "fmt-unhide-columns",
    keys: [["Ctrl", "Shift", "0"]],
    action: "Unhide the hidden columns inside the selection",
    category: "formatting",
    note: "Some Windows keyboard layout settings claim this combination, in which case use the ribbon route Alt, H, O, U, L",
  },
  {
    id: "fmt-style-dialog",
    keys: [["Alt", "'"]],
    action: "Open the Style dialog",
    category: "formatting",
  },
  {
    id: "fmt-autofit-column-width",
    keys: [["Alt"], ["H"], ["O"], ["I"]],
    action: "Fit the column width to the widest entry",
    category: "formatting",
  },
  {
    id: "fmt-autofit-row-height",
    keys: [["Alt"], ["H"], ["O"], ["A"]],
    action: "Fit the row height to the tallest entry",
    category: "formatting",
  },
  {
    id: "fmt-column-width",
    keys: [["Alt"], ["H"], ["O"], ["W"]],
    action: "Set an exact column width",
    category: "formatting",
  },
  {
    id: "fmt-row-height",
    keys: [["Alt"], ["H"], ["O"], ["H"]],
    action: "Set an exact row height",
    category: "formatting",
  },
  {
    id: "fmt-merge-and-center",
    keys: [["Alt"], ["H"], ["M"], ["C"]],
    action: "Merge the selected cells and centre the contents",
    category: "formatting",
  },
  {
    id: "fmt-unmerge",
    keys: [["Alt"], ["H"], ["M"], ["U"]],
    action: "Split merged cells back apart",
    category: "formatting",
  },
  {
    id: "fmt-wrap-text",
    keys: [["Alt"], ["H"], ["W"]],
    action: "Turn text wrapping on or off",
    category: "formatting",
  },
  {
    id: "fmt-increase-decimal",
    keys: [["Alt"], ["H"], ["0"]],
    action: "Show one more decimal place",
    category: "formatting",
  },
  {
    id: "fmt-decrease-decimal",
    keys: [["Alt"], ["H"], ["9"]],
    action: "Show one fewer decimal place",
    category: "formatting",
  },
  {
    id: "fmt-align-left",
    keys: [["Alt"], ["H"], ["A"], ["L"]],
    action: "Align the contents to the left",
    category: "formatting",
  },
  {
    id: "fmt-align-center",
    keys: [["Alt"], ["H"], ["A"], ["C"]],
    action: "Centre the contents horizontally",
    category: "formatting",
  },
  {
    id: "fmt-align-right",
    keys: [["Alt"], ["H"], ["A"], ["R"]],
    action: "Align the contents to the right",
    category: "formatting",
  },
  {
    id: "fmt-align-top",
    keys: [["Alt"], ["H"], ["A"], ["T"]],
    action: "Align the contents to the top of the cell",
    category: "formatting",
  },
  {
    id: "fmt-align-middle",
    keys: [["Alt"], ["H"], ["A"], ["M"]],
    action: "Centre the contents vertically",
    category: "formatting",
  },
  {
    id: "fmt-align-bottom",
    keys: [["Alt"], ["H"], ["A"], ["B"]],
    action: "Align the contents to the bottom of the cell",
    category: "formatting",
  },
  {
    id: "fmt-borders-menu",
    keys: [["Alt"], ["H"], ["B"]],
    action: "Open the borders menu",
    category: "formatting",
  },
  {
    id: "fmt-fill-colour",
    keys: [["Alt"], ["H"], ["H"]],
    action: "Open the fill colour picker",
    category: "formatting",
  },
  {
    id: "fmt-font-colour",
    keys: [["Alt"], ["H"], ["F"], ["C"]],
    action: "Open the font colour picker",
    category: "formatting",
  },
  {
    id: "fmt-format-painter",
    keys: [["Alt"], ["H"], ["F"], ["P"]],
    action:
      "Pick up the formatting of the selection to brush onto another range",
    category: "formatting",
  },
  {
    id: "fmt-conditional-formatting",
    keys: [["Alt"], ["H"], ["L"]],
    action: "Open the conditional formatting menu",
    category: "formatting",
  },
  {
    id: "fmt-clear-formats",
    keys: [["Alt"], ["H"], ["E"], ["F"]],
    action: "Clear the formatting and keep the contents",
    category: "formatting",
  },
  {
    id: "fmt-number-format-menu",
    keys: [["Alt"], ["H"], ["N"]],
    action: "Open the number format list on the Home tab",
    category: "formatting",
  },

  // Formulas
  {
    id: "for-start-formula",
    keys: [["="]],
    action: "Start a formula in the active cell",
    category: "formulas",
  },
  {
    id: "for-autosum",
    keys: [["Alt", "="]],
    action: "Insert a SUM formula for the range above or to the left",
    category: "formulas",
  },
  {
    id: "for-array-formula",
    keys: [["Ctrl", "Shift", "Enter"]],
    action: "Confirm the formula as a legacy array formula",
    category: "formulas",
    note: "Builds that support dynamic arrays spill without it",
  },
  {
    id: "for-show-formulas",
    keys: [["Ctrl", "`"]],
    action: "Show the formulas in the cells instead of their results",
    category: "formulas",
  },
  {
    id: "for-insert-function",
    keys: [["Shift", "F3"]],
    action: "Open the Insert Function dialog",
    category: "formulas",
  },
  {
    id: "for-argument-names",
    keys: [["Ctrl", "Shift", "A"]],
    action: "Insert the argument names of the function just typed",
    category: "formulas",
  },
  {
    id: "for-paste-name",
    keys: [["F3"]],
    action: "Paste a defined name into the formula",
    category: "formulas",
    note: "Available once the workbook has at least one defined name",
  },
  {
    id: "for-name-manager",
    keys: [["Ctrl", "F3"]],
    action: "Open the Name Manager",
    category: "formulas",
  },
  {
    id: "for-create-names",
    keys: [["Ctrl", "Shift", "F3"]],
    action: "Create defined names from the labels in the selection",
    category: "formulas",
  },
  {
    id: "for-calculate-all",
    keys: [["F9"]],
    action: "Calculate the formulas that changed in the open workbooks",
    category: "formulas",
    note: "While editing a formula it replaces the selected part with its current value",
  },
  {
    id: "for-calculate-sheet",
    keys: [["Shift", "F9"]],
    action: "Calculate the active worksheet only",
    category: "formulas",
  },
  {
    id: "for-calculate-full",
    keys: [["Ctrl", "Alt", "F9"]],
    action: "Recalculate the open workbooks, changed or not",
    category: "formulas",
  },
  {
    id: "for-calculate-rebuild",
    keys: [["Ctrl", "Alt", "Shift", "F9"]],
    action: "Rebuild the dependency tree and recalculate the open workbooks",
    category: "formulas",
  },
  {
    id: "for-trace-precedents",
    keys: [["Ctrl", "["]],
    action: "Select the cells the formula in the active cell refers to",
    category: "formulas",
  },
  {
    id: "for-trace-dependents",
    keys: [["Ctrl", "]"]],
    action: "Select the formulas that refer to the active cell",
    category: "formulas",
  },
  {
    id: "for-trace-all-precedents",
    keys: [["Ctrl", "Shift", "["]],
    action:
      "Select the cells the active formula depends on, directly and indirectly",
    category: "formulas",
    note: "Published as Ctrl+Shift+{",
  },
  {
    id: "for-trace-all-dependents",
    keys: [["Ctrl", "Shift", "]"]],
    action:
      "Select the formulas that depend on the active cell, directly and indirectly",
    category: "formulas",
    note: "Published as Ctrl+Shift+}",
  },
  {
    id: "for-define-name",
    keys: [["Alt"], ["M"], ["M"], ["D"]],
    action: "Define a name for the selection",
    category: "formulas",
  },
  {
    id: "for-trace-precedent-arrows",
    keys: [["Alt"], ["M"], ["P"]],
    action: "Draw arrows to the cells the active formula refers to",
    category: "formulas",
  },
  {
    id: "for-trace-dependent-arrows",
    keys: [["Alt"], ["M"], ["D"]],
    action: "Draw arrows to the formulas that refer to the active cell",
    category: "formulas",
  },
  {
    id: "for-remove-arrows",
    keys: [["Alt"], ["M"], ["A"], ["A"]],
    action: "Remove the tracing arrows from the worksheet",
    category: "formulas",
  },
  {
    id: "for-evaluate-formula",
    keys: [["Alt"], ["M"], ["V"]],
    action: "Step through the formula in the Evaluate Formula dialog",
    category: "formulas",
  },
  {
    id: "for-calculation-options",
    keys: [["Alt"], ["M"], ["X"]],
    action: "Open the calculation options, where automatic and manual are set",
    category: "formulas",
  },

  // Tables and filtering
  {
    id: "tbl-create-table",
    keys: [["Ctrl", "T"]],
    action: "Turn the selected range into an Excel table",
    category: "tables and filtering",
  },
  {
    id: "tbl-create-table-alternate",
    keys: [["Ctrl", "L"]],
    action: "Open the same Create Table dialog as Ctrl+T",
    category: "tables and filtering",
  },
  {
    id: "tbl-toggle-filters",
    keys: [["Ctrl", "Shift", "L"]],
    action: "Add or remove the filter row",
    category: "tables and filtering",
  },
  {
    id: "tbl-filter-ribbon",
    keys: [["Alt"], ["A"], ["T"]],
    action: "Add or remove the filter row from the Data tab",
    category: "tables and filtering",
  },
  {
    id: "tbl-clear-filters",
    keys: [["Alt"], ["A"], ["C"]],
    action: "Clear the filters on the current sheet",
    category: "tables and filtering",
  },
  {
    id: "tbl-sort-dialog",
    keys: [["Alt"], ["A"], ["S"], ["S"]],
    action: "Open the Sort dialog for multi-level sorting",
    category: "tables and filtering",
  },
  {
    id: "tbl-sort-ascending",
    keys: [["Alt"], ["A"], ["S"], ["A"]],
    action: "Sort the current column in ascending order",
    category: "tables and filtering",
  },
  {
    id: "tbl-sort-descending",
    keys: [["Alt"], ["A"], ["S"], ["D"]],
    action: "Sort the current column in descending order",
    category: "tables and filtering",
  },
  {
    id: "tbl-remove-duplicates",
    keys: [["Alt"], ["A"], ["M"]],
    action: "Open Remove Duplicates for the selected range",
    category: "tables and filtering",
  },
  {
    id: "tbl-text-to-columns",
    keys: [["Alt"], ["A"], ["E"]],
    action: "Open the Text to Columns wizard",
    category: "tables and filtering",
  },
  {
    id: "tbl-data-validation",
    keys: [["Alt"], ["A"], ["V"], ["V"]],
    action: "Open the Data Validation dialog",
    category: "tables and filtering",
  },
  {
    id: "tbl-refresh-all",
    keys: [["Alt"], ["A"], ["R"], ["A"]],
    action: "Refresh the workbook's queries and connections",
    category: "tables and filtering",
  },
  {
    id: "tbl-advanced-filter",
    keys: [["Alt"], ["A"], ["Q"]],
    action: "Open the Advanced Filter dialog",
    category: "tables and filtering",
  },
  {
    id: "tbl-subtotal",
    keys: [["Alt"], ["A"], ["B"]],
    action: "Open the Subtotal dialog for a sorted list",
    category: "tables and filtering",
  },
  {
    id: "tbl-group",
    keys: [["Alt"], ["A"], ["G"], ["G"]],
    action: "Group the selected rows or columns into an outline",
    category: "tables and filtering",
  },
  {
    id: "tbl-ungroup",
    keys: [["Alt"], ["A"], ["U"], ["U"]],
    action: "Ungroup the selected rows or columns",
    category: "tables and filtering",
  },
  {
    id: "tbl-outline-symbols",
    keys: [["Ctrl", "8"]],
    action: "Show or hide the outline symbols beside a grouped range",
    category: "tables and filtering",
  },
  {
    id: "tbl-legacy-filter",
    keys: [["Alt"], ["D"], ["F"], ["F"]],
    action: "Add or remove the filter row through the older menu route",
    category: "tables and filtering",
  },

  // Pivot tables
  {
    id: "pivot-insert",
    keys: [["Alt"], ["N"], ["V"]],
    action: "Start inserting a PivotTable from the Insert tab",
    category: "pivot tables",
    note: "Recent builds add one more step for the data source",
  },
  {
    id: "pivot-wizard",
    keys: [["Alt"], ["D"], ["P"]],
    action: "Open the older PivotTable and PivotChart Wizard",
    category: "pivot tables",
    note: "Useful for consolidating several ranges into one report",
  },
  {
    id: "pivot-refresh",
    keys: [["Alt", "F5"]],
    action: "Refresh the PivotTable under the cursor",
    category: "pivot tables",
  },
  {
    id: "pivot-refresh-all",
    keys: [["Ctrl", "Alt", "F5"]],
    action: "Refresh the data connections and PivotTables in the workbook",
    category: "pivot tables",
  },
  {
    id: "pivot-group",
    keys: [["Alt", "Shift", "ArrowRight"]],
    action: "Group the selected PivotTable items",
    category: "pivot tables",
  },
  {
    id: "pivot-ungroup",
    keys: [["Alt", "Shift", "ArrowLeft"]],
    action: "Ungroup the selected PivotTable items",
    category: "pivot tables",
  },
  {
    id: "pivot-analyze-tab",
    keys: [["Alt"], ["J"], ["T"]],
    action: "Open the PivotTable Analyze tab",
    category: "pivot tables",
    note: "The contextual tabs only appear while the cursor sits inside a PivotTable",
  },

  // Workbook and window
  {
    id: "wb-new",
    keys: [["Ctrl", "N"]],
    action: "Create a new workbook",
    category: "workbook and window",
  },
  {
    id: "wb-open",
    keys: [["Ctrl", "O"]],
    action: "Open an existing workbook",
    category: "workbook and window",
  },
  {
    id: "wb-save",
    keys: [["Ctrl", "S"]],
    action: "Save the workbook",
    category: "workbook and window",
  },
  {
    id: "wb-save-as",
    keys: [["F12"]],
    action: "Open Save As to write a new file",
    category: "workbook and window",
  },
  {
    id: "wb-print",
    keys: [["Ctrl", "P"]],
    action: "Open the print settings",
    category: "workbook and window",
  },
  {
    id: "wb-print-preview",
    keys: [["Ctrl", "F2"]],
    action: "Open the print preview",
    category: "workbook and window",
  },
  {
    id: "wb-close-workbook",
    keys: [["Ctrl", "W"]],
    action: "Close the active workbook",
    category: "workbook and window",
  },
  {
    id: "wb-close-window",
    keys: [["Ctrl", "F4"]],
    action: "Close the active workbook window",
    category: "workbook and window",
  },
  {
    id: "wb-quit",
    keys: [["Alt", "F4"]],
    action: "Close Excel",
    category: "workbook and window",
  },
  {
    id: "wb-next-workbook",
    keys: [["Ctrl", "Tab"]],
    action: "Move to the next open workbook window",
    category: "workbook and window",
  },
  {
    id: "wb-previous-workbook",
    keys: [["Ctrl", "Shift", "Tab"]],
    action: "Move to the previous open workbook window",
    category: "workbook and window",
  },
  {
    id: "wb-next-window-f6",
    keys: [["Ctrl", "F6"]],
    action: "Move to the next workbook window",
    category: "workbook and window",
  },
  {
    id: "wb-previous-window-f6",
    keys: [["Ctrl", "Shift", "F6"]],
    action: "Move to the previous workbook window",
    category: "workbook and window",
  },
  {
    id: "wb-minimize",
    keys: [["Ctrl", "F9"]],
    action: "Minimise the workbook window",
    category: "workbook and window",
  },
  {
    id: "wb-maximize",
    keys: [["Ctrl", "F10"]],
    action: "Maximise or restore the workbook window",
    category: "workbook and window",
  },
  {
    id: "wb-restore-size",
    keys: [["Ctrl", "F5"]],
    action: "Restore the size of the workbook window",
    category: "workbook and window",
  },
  {
    id: "wb-move-window",
    keys: [["Ctrl", "F7"]],
    action: "Move the workbook window with the arrow keys",
    category: "workbook and window",
    note: "Available while the window is not maximised",
  },
  {
    id: "wb-size-window",
    keys: [["Ctrl", "F8"]],
    action: "Resize the workbook window with the arrow keys",
    category: "workbook and window",
  },
  {
    id: "wb-insert-worksheet",
    keys: [["Shift", "F11"]],
    action: "Insert a new worksheet",
    category: "workbook and window",
  },
  {
    id: "wb-freeze-panes",
    keys: [["Alt"], ["W"], ["F"], ["F"]],
    action: "Freeze the rows above and the columns left of the active cell",
    category: "workbook and window",
  },
  {
    id: "wb-freeze-top-row",
    keys: [["Alt"], ["W"], ["F"], ["R"]],
    action: "Freeze the top row",
    category: "workbook and window",
  },
  {
    id: "wb-freeze-first-column",
    keys: [["Alt"], ["W"], ["F"], ["C"]],
    action: "Freeze the first column",
    category: "workbook and window",
  },
  {
    id: "wb-split",
    keys: [["Alt"], ["W"], ["S"]],
    action: "Split the window into scrollable panes",
    category: "workbook and window",
  },
  {
    id: "wb-zoom",
    keys: [["Alt"], ["W"], ["Q"]],
    action: "Open the Zoom dialog",
    category: "workbook and window",
  },
  {
    id: "wb-new-window",
    keys: [["Alt"], ["W"], ["N"]],
    action: "Open a second window onto the same workbook",
    category: "workbook and window",
  },
  {
    id: "wb-arrange-all",
    keys: [["Alt"], ["W"], ["A"]],
    action:
      "Open the Arrange Windows dialog to tile or cascade the open workbooks",
    category: "workbook and window",
  },
  {
    id: "wb-normal-view",
    keys: [["Alt"], ["W"], ["L"]],
    action: "Switch to the normal view",
    category: "workbook and window",
  },
  {
    id: "wb-page-break-preview",
    keys: [["Alt"], ["W"], ["I"]],
    action: "Switch to the page break preview",
    category: "workbook and window",
  },
  {
    id: "wb-rename-sheet",
    keys: [["Alt"], ["H"], ["O"], ["R"]],
    action: "Rename the active worksheet",
    category: "workbook and window",
  },
  {
    id: "wb-move-or-copy-sheet",
    keys: [["Alt"], ["H"], ["O"], ["M"]],
    action: "Open Move or Copy for the active worksheet",
    category: "workbook and window",
  },
  {
    id: "wb-tab-colour",
    keys: [["Alt"], ["H"], ["O"], ["T"]],
    action: "Set the colour of the worksheet tab",
    category: "workbook and window",
  },
  {
    id: "wb-delete-sheet",
    keys: [["Alt"], ["H"], ["D"], ["S"]],
    action: "Delete the active worksheet",
    category: "workbook and window",
    note: "Deleting a sheet cannot be undone",
  },
  {
    id: "wb-insert-sheet-ribbon",
    keys: [["Alt"], ["H"], ["I"], ["S"]],
    action: "Insert a worksheet from the ribbon",
    category: "workbook and window",
  },
  {
    id: "wb-hide-sheet",
    keys: [["Alt"], ["H"], ["O"], ["U"], ["S"]],
    action: "Hide the active worksheet",
    category: "workbook and window",
  },

  // Ribbon sequences
  {
    id: "ribbon-key-tips",
    keys: [["Alt"]],
    action: "Show the ribbon key tips, then type the letters they display",
    category: "ribbon sequences",
    note: "The multi-step routes here, the ones whose first step is Alt on its own, are read from those key tips. A chord such as Alt+Enter is not one of them",
  },
  {
    id: "ribbon-key-tips-f10",
    keys: [["F10"]],
    action: "Show the ribbon key tips",
    category: "ribbon sequences",
    note: "The same as pressing Alt",
  },
  {
    id: "ribbon-home-tab",
    keys: [["Alt"], ["H"]],
    action: "Open the Home tab",
    category: "ribbon sequences",
  },
  {
    id: "ribbon-insert-tab",
    keys: [["Alt"], ["N"]],
    action: "Open the Insert tab",
    category: "ribbon sequences",
  },
  {
    id: "ribbon-page-layout-tab",
    keys: [["Alt"], ["P"]],
    action: "Open the Page Layout tab",
    category: "ribbon sequences",
  },
  {
    id: "ribbon-formulas-tab",
    keys: [["Alt"], ["M"]],
    action: "Open the Formulas tab",
    category: "ribbon sequences",
  },
  {
    id: "ribbon-data-tab",
    keys: [["Alt"], ["A"]],
    action: "Open the Data tab",
    category: "ribbon sequences",
  },
  {
    id: "ribbon-review-tab",
    keys: [["Alt"], ["R"]],
    action: "Open the Review tab",
    category: "ribbon sequences",
  },
  {
    id: "ribbon-view-tab",
    keys: [["Alt"], ["W"]],
    action: "Open the View tab",
    category: "ribbon sequences",
  },
  {
    id: "ribbon-file-menu",
    keys: [["Alt"], ["F"]],
    action: "Open the File menu",
    category: "ribbon sequences",
  },
  {
    id: "ribbon-search",
    keys: [["Alt"], ["Q"]],
    action: "Jump to the search box that runs ribbon commands by name",
    category: "ribbon sequences",
  },
  {
    id: "ribbon-file-new",
    keys: [["Alt"], ["F"], ["N"]],
    action: "Open the New page of the File menu",
    category: "ribbon sequences",
  },
  {
    id: "ribbon-file-open",
    keys: [["Alt"], ["F"], ["O"]],
    action: "Open the Open page of the File menu",
    category: "ribbon sequences",
  },
  {
    id: "ribbon-file-save",
    keys: [["Alt"], ["F"], ["S"]],
    action: "Save the workbook from the File menu",
    category: "ribbon sequences",
  },
  {
    id: "ribbon-file-save-as",
    keys: [["Alt"], ["F"], ["A"]],
    action: "Open the Save As page of the File menu",
    category: "ribbon sequences",
  },
  {
    id: "ribbon-file-print",
    keys: [["Alt"], ["F"], ["P"]],
    action: "Open the Print page of the File menu",
    category: "ribbon sequences",
  },
  {
    id: "ribbon-file-info",
    keys: [["Alt"], ["F"], ["I"]],
    action: "Open the Info page of the File menu",
    category: "ribbon sequences",
  },
  {
    id: "ribbon-file-export",
    keys: [["Alt"], ["F"], ["E"]],
    action: "Open the Export page of the File menu",
    category: "ribbon sequences",
  },
  {
    id: "ribbon-file-close",
    keys: [["Alt"], ["F"], ["C"]],
    action: "Close the workbook from the File menu",
    category: "ribbon sequences",
  },
  {
    id: "ribbon-file-options",
    keys: [["Alt"], ["F"], ["T"]],
    action: "Open the Excel options",
    category: "ribbon sequences",
  },
  {
    id: "ribbon-collapse",
    keys: [["Ctrl", "F1"]],
    action: "Collapse or expand the ribbon",
    category: "ribbon sequences",
  },
  {
    id: "ribbon-quick-access-first",
    keys: [["Alt"], ["1"]],
    action: "Run the first command on the Quick Access Toolbar",
    category: "ribbon sequences",
    note: "The number matches the position of the command on that toolbar",
  },
  {
    id: "ribbon-quick-access-second",
    keys: [["Alt"], ["2"]],
    action: "Run the second command on the Quick Access Toolbar",
    category: "ribbon sequences",
  },

  // Other
  {
    id: "oth-help",
    keys: [["F1"]],
    action: "Open Help",
    category: "other",
  },
  {
    id: "oth-context-menu",
    keys: [["Shift", "F10"]],
    action: "Open the context menu for the selection",
    category: "other",
    note: "The same menu a right click opens",
  },
  {
    id: "oth-spelling",
    keys: [["F7"]],
    action: "Check the spelling on the worksheet",
    category: "other",
  },
  {
    id: "oth-thesaurus",
    keys: [["Shift", "F7"]],
    action: "Open the thesaurus for the active cell",
    category: "other",
  },
  {
    id: "oth-macro-dialog",
    keys: [["Alt", "F8"]],
    action: "Open the Macro dialog",
    category: "other",
  },
  {
    id: "oth-visual-basic-editor",
    keys: [["Alt", "F11"]],
    action: "Open the Visual Basic editor",
    category: "other",
  },
  {
    id: "oth-chart-on-sheet",
    keys: [["Alt", "F1"]],
    action: "Create a chart from the selected data on the current worksheet",
    category: "other",
  },
  {
    id: "oth-chart-sheet",
    keys: [["F11"]],
    action: "Create a chart from the selected data on a new chart sheet",
    category: "other",
  },
  {
    id: "oth-toggle-objects",
    keys: [["Ctrl", "6"]],
    action: "Show or hide the objects that sit over the grid",
    category: "other",
  },
  {
    id: "oth-edit-note",
    keys: [["Shift", "F2"]],
    action: "Add or edit a note on the active cell",
    category: "other",
  },
  {
    id: "oth-protect-sheet",
    keys: [["Alt"], ["R"], ["P"], ["S"]],
    action: "Open the Protect Sheet dialog",
    category: "other",
  },
  {
    id: "oth-protect-workbook",
    keys: [["Alt"], ["R"], ["P"], ["W"]],
    action: "Open the Protect Workbook dialog",
    category: "other",
  },
];
